### ISSUE TITLE
Adapter implementation

### ISSUE THREAD

**Issue by corradopetrelli** [tim-hellhake/azure-iot-bridge#4]
I do not understand. Where is the implementation of "Adapter"? I found only the declaration on d.ts file.

Sorry for the dumb question.

**Comment by tim-hellhake** [comment]
> Sorry for the dumb question.

No need to apologize :)

> Where is the implementation of "Adapter"?

It is [here](https://github.com/tim-hellhake/azure-iot-bridge/blob/master/src/azure-iot-bridge.ts).

**Comment by corradopetrelli** [comment]
Thanks!

I wanted to commend you on the work done!

**Comment by tim-hellhake** [comment]
I'm closing this now.
If you have any further questions, feel free to ask.
